#!/bin/bash

deactivate
set -e
set -x

# gather VM name
hostname; whoami

# method to prep the VM
venv () {
    venv=/projects/stars/var/GTEx/GTExVenv
    if [ ! -d $venv ]; then
        python3.6 -m venv $venv
        source $venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    fi

    source $venv/bin/activate
}

# call for VM prep
venv

# move to the  GTEX staging area
cd /projects/stars/var/GTEx/stage/smartBag/

# clone the entire repo
# note using a pull here implies you are using the correct repo branch
git pull https://github.com/NCATS-Tangerine/smartBag.git

# export the current directory
export PATH=$PWD/bin:$PATH
echo $PATH

# go to the target project to process
cd example/GTEx

# run the configuration script. this also creates the smartbag archive
./configure

// go to the smartBag API directory to create the site
cd ../../bin

# decompress the smart bag and load the API
./smartbag make smartapi --bag ../example/GTEx/bag.tgz --opts ../example/GTEx/options.json

# go to the directory with the docker file
cd ../example/GTEx

# create the docker image and launch the container
docker build --tag=smartbag_gtex .
docker run -it -v /projects/stars/var/GTEx/stage/smartBag/bin:/smartBag -p 4000:5000 -d smartbag_gtex

# alternativly you can start the website in the running instance
# start/run the API website
#./smartbag run smartapi --port 5000
