#!/bin/bash

deactivate
set -e
set -x

hostname; whoami
mkdir -p $HOSTNAME
cd $HOSTNAME
rm -rf smartBag

git clone https://github.com/NCATS-Tangerine/smartBag.git

venv () {
    venv=/projects/stars/biclusterVenv
    if [ ! -d $venv ]; then
        python3.6 -m venv $venv
    fi
    source $venv/bin/activate
}
venv

cd smartBag

export PATH=$PWD/bin:$PATH
echo $PATH

pip install --upgrade pip
pip install -r requirements.txt

cd example/bicluster
./configure $1
smartbag make bag
smartbag make smartapi --bag bag.tgz --title bicluster
smartbag run smartapi
