#!/bin/bash

deactivate
set -e
set -x

hostname; whoami
mkdir -p $HOSTNAME
cd $HOSTNAME
rm -rf smartBag

git clone https://github.com/NCATS-Tangerine/smartBag.git

export PATH=smartBag/bin:$PATH

venv () {
    venv=/projects/stars/ctdVenv
    if [ ! -d $venv ]; then
        python3.6 -m venv $venv
    fi
    source $venv/bin/activate
}
#venv

cd smartBag
pip install -r requirements.txt

cd examples/ctd
./configure $1
smartbag make bag
smartbag make smartapi --bag bag.tgz --title CTD
smartbag run smartapi
