#!/bin/bash

deactivate
set -e
set -x

hostname; whoami
cd /projects/stars/var/ctd_data/stage

mkdir -p $HOSTNAME
cd $HOSTNAME
rm -rf smartBag

git clone https://github.com/NCATS-Tangerine/smartBag.git

venv () {
    venv=/projects/stars/ctdVenv
    if [ ! -d $venv ]; then
        python3.6 -m venv $venv
        source $venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    fi
    source $venv/bin/activate
}
venv

cd smartBag
export PATH=$PWD/bin:$PATH
echo $PATH

cd example/ctd
./configure $1
smartbag make bag
bin/smartbag make smartapi --bag example/ctd/bag.tgz --opts example/ctd/options.json
smartbag run smartapi --port 8997
