#!/bin/bash

deactivate
set -e
set -x

hostname; whoami

# change to the temporary data directory
cd /projects/stars/var/bicluster_data/stage

mkdir -p $HOSTNAME
cd $HOSTNAME
rm -rf smartBag

git clone https://github.com/NCATS-Tangerine/smartBag.git
cd smartBag
#git checkout phil_smartBag

venv () {
    venv=/projects/stars/var/bicluster_data/biclusterVenv
    if [ ! -d $venv ]; then
        python3.6 -m venv $venv
        source $venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    fi
    source $venv/bin/activate
}
venv

export PATH=$PWD/bin:$PATH
echo $PATH

cd endpoints/bicluster

./configure $1

smartbag make bag
cd ../../bin

./smartbag make smartapi --bag ../endpoints/bicluster/bag.tgz --opts ../endpoints/bicluster/options.json
cd ../endpoints/bicluster

docker build --tag=smartbag_bicluster .
docker run -it -v /projects/stars/var/bicluster_data/stage/$HOSTNAME/smartBag/bin:/smartBag -p 4003:5003 -d smartbag_bicluster

#smartbag run smartapi
