#!/bin/bash

deactivate
set -e
set -x

hostname; whoami
mkdir -p $HOSTNAME
cd $HOSTNAME
rm -rf smartBag

git clone https://github.com/NCATS-Tangerine/smartBag.git

venv=/projects/stars/ctdVenv
if [ ! -d $venv ]; then
   python3.6 -m venv $venv
fi
source $venv/bin/activate

cd smartBag
pip install -r requirements.txt

cd ctd
./all"
