#!/bin/bash

files="
http://ctdbase.org/reports/CTD_chem_gene_ixns.csv.gz
http://ctdbase.org/reports/CTD_chem_gene_ixn_types.csv
http://ctdbase.org/reports/CTD_chemicals_diseases.csv.gz
http://ctdbase.org/reports/CTD_chem_go_enriched.csv.gz
http://ctdbase.org/reports/CTD_chem_pathways_enriched.csv.gz
http://ctdbase.org/reports/CTD_genes_diseases.csv.gz
http://ctdbase.org/reports/CTD_genes_pathways.csv.gz
http://ctdbase.org/reports/CTD_diseases_pathways.csv.gz
http://ctdbase.org/reports/CTD_exposure_studies.csv.gz
http://ctdbase.org/reports/CTD_exposure_events.csv.gz
http://ctdbase.org/reports/CTD_Disease-GO_biological_process_associations.csv.gz
http://ctdbase.org/reports/CTD_Disease-GO_cellular_component_associations.csv.gz
http://ctdbase.org/reports/CTD_Disease-GO_molecular_function_associations.csv.gz
http://ctdbase.org/reports/CTD_chemicals.csv.gz
http://ctdbase.org/reports/CTD_diseases.csv.gz
http://ctdbase.org/reports/CTD_genes.csv.gz
http://ctdbase.org/reports/CTD_pathways.csv.gz
"
for f in $files; do
    echo $f
    wget --quiet --timestamping $f
done
